### ISSUE TITLE
Install the theme and enable custom website in odoo/modules with Ansible

### ISSUE THREAD

**Issue by thepian** [ignorethegap/modular-apps#19]
The existing repository contains custom Odoo modules for a sample add-on and a theme. They are placeholders and can be adjusted to make things work, but must be part of the installation without any special copying into the VM. They are already shared in the VM under `/vagrant/odoo/modules`.
- [x] theme in odoo/modules is active after vagrant up
- [x] http://localhost:8069 shows the website in odoo/modules/homepage
- [x] other modules in odoo/modules are installed

**Comment by thepian** [comment]
If you like you can put any free theme in odoo/modules and make it take effect with the default localhost:8069 page

**Comment by khalturinsky** [comment]
fix
