### ISSUE TITLE
Make a backup of demo data and restore it with Ansible

### ISSUE THREAD

**Issue by thepian** [ignorethegap/modular-apps#20]
Instructions must be added for how to export a new DB backup to the Git repository.
- [x] Save a database backup of the `odoo` database to the Git repository under `odoo/odoo-db-test-data.sql`
- [x] Use Ansible to create and restore the `odoo` database from `odoo/odoo-db-test-data.sql` as an odoo task

**Comment by khalturinsky** [comment]
What means "as an odoo task"? - it is ansible role? or ooo system have task instrument?
